mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import polls.views as views


urlpatterns = [
    path('polls/', include('polls.urls', namespace='polls')),
    path('admin/', admin.site.urls),
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
]

polls/urls.py
from django.urls import path, include

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('account/',include('django.contrib.auth.urls')),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Product(models.Model):
    upccode = models.CharField('UPC code',max_length=14)
    description = models.CharField('Description', max_length=60)
    price = models.DecimalField("Unit Price", 
            max_digits=9, decimal_places=2)

    def quantity_in_stock(self):
        """Compute and return number of units in stock"""

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from .models import Choice, Question

import logging

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def index(request):
    return HttpResponseRedirect(reverse("polls:index"))


def configure():
    """Configure loggers and log handlers"""
    filehandler = logging.FileHandler("demo.log")
    filehandler.setLevel(logging.NOTSET)
    formatter = logging.Formatter('%(asctime)s %(name)s %(levelname)s: %(message)s')
    filehandler.setFormatter(formatter)

    root = logging.getLogger()
    root.addHandler(filehandler)

    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.WARNING)
    formatter = logging.Formatter(fmt='%(levelname)-8s %(name)s: %(message)s')
    console_handler.setFormatter(formatter)
    root.addHandler(console_handler)

class EyesOnlyView(LoginRequiredMixin, generic.ListView):
    # this is the default. Same default as in auth_required decorator
    login_url = '/accounts/login/'

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        configure()
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        configure()
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    configure()

@login_required(login_url='/accounts/login/')
def vote(request, question_id):
    """Vote for one of the answers to a question."""
    user = request.user
    print("current user is", user.id, "login", user.username)
    print("Real name:", user.first_name, user.last_name)
    question = get_object_or_404(Question, pk=question_id)
    try:
        configure()
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        configure()
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        configure()
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" type = "text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>
    <hr>Header<hr>
    {% block main_content %}
    {% endblock %}
    
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if user.is_authenticated %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% else %}
    <form>
        {% endif %}
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        {% if user.is_authenticated %}
        <input type="submit" value="Vote" id="submit_vote">
        {% else %}
        <br>
        Please <a value"login" href="{% url 'login' %}?next={{ request.path }}">login</a> to vote
        {% endif %}
    </form>
    <a href="{% url 'polls:results' question.id %}">See result</a>
    <br>
    <a href="{% url 'polls:index' %}">
        <-- Back to question list</a> {% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

{% if user.is_authenticated %}
Welcome back,
{% if user.first_name != '' %}
{{ user.first_name }}
{% else %}
{{ user.username.title }}!
{% endif %}
{% else %}
<h3>Please <a href="{% url 'login' %}">login</a> to vote for a topics</h3>
{% endif %}
<h2>Available Polls</h2>
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a name="question" href="{% url 'polls:detail' question.id %}" id="question{{ question.id }}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Logout</a>
{% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <table>
        <tr><th>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </th></tr>
    </table>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<br>
<a href="{% url 'polls:index' %}"> <-- Back to question list</a>


{% endblock %}